FROM node:22-alpine
WORKDIR /case-front
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli@15
COPY . .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check", "--proxy-config", "proxy.conf.json"]
